export const tournaments = [
  {
    id: 1,
    title: "Summer Showdown",
    games: [
      {
        name: "Valorant",
        registrationFee: "Rs 200",
        type: "team",
        teamSize: 5,
      },
      { name: "CS:GO", registrationFee: "Rs 300", type: "team", teamSize: 5 },
    ],
    date: "July 20, 2025",
    time: "6:00 PM",
    location: "Online",
    price: "Paid",
    registrationFee: "Rs 100",
    image: "/img/tournament1.png",
    description: "🔥 Multi-game bracket. Compete in FPS and mobile titles!",
    status: "ongoing",
    type: "team",
    teamSize: 5,
  },
  {
    id: 2,
    title: "Smash Bash",
    games: [
      { name: "Smash Bros", registrationFee: "Rs 150", type: "single" },
      { name: "Tekken 7", registrationFee: "Rs 150", type: "single" },
    ],
    date: "July 22, 2025",
    time: "3:00 PM",
    location: "Faisalabad Arena",
    price: "Paid",
    registrationFee: "Rs 200",
    image: "/img/tournament2.png",
    description: "⚔️ Face off in classic console brawlers!",
    status: "upcoming",
    type: "single",
  },
  {
    id: 3,
    title: "Mobile Mayhem",
    games: [
      { name: "Clash Royale", registrationFee: "Rs 50", type: "single" },
      {
        name: "Free Fire",
        registrationFee: "Rs 100",
        type: "team",
        teamSize: 2,
      },
      {
        name: "Brawl Stars",
        registrationFee: "Rs 80",
        type: "team",
        teamSize: 3,
      },
    ],
    date: "July 25, 2025",
    time: "5:00 PM",
    location: "Online",
    price: "Paid",
    registrationFee: "Rs 50",
    image: "/img/tornament3.png",
    description: "📱 Mobile gamers unite in a high-stakes tournament event.",
    status: "complete",
    type: "team",
    teamSize: 3,
  },
];
