import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Optional: move this metadata to `app/head.js` if needed in JS-only project
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          toastOptions={{
            success: {
              style: {
                background: "var(--background)",
                color: "#fff",
                border: "1px solid #22c55e",
              },
            },
            error: {
              style: {
                background: "var(--background)",
                color: "#fecaca",
                border: "1px solid #f87171",
              },
            },
          }}
        />

        {children}
      </body>
    </html>
  );
}
