
import "./globals.css";

import { Toaster } from "react-hot-toast";


// Optional: move this metadata to `app/head.js` if needed in JS-only project
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Toaster
          position="top-center"
          toastOptions={{
            success: {
              style: {
                background: "var(--background)",
                color: "#fff",
                border: "1px solid #22c55e",
              },
            },
            error: {
              style: {
                background: "var(--background)",
                color: "#fecaca",
                border: "1px solid #f87171",
              },
            },
          }}
        />

        {children}
      </body>
    </html>
  );
}
